# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14b59ae6996f15e3d01e925d7897a7250dba9fd3552956885e87f4f81da527e73f342769cc290e496531779ee838bbb42c06a39b2284bee99c2ce67054ede3b1

test:
  secret_key_base: ee7c9a2842611ea604eac2486342526069398848135eb0c8f7c70b86b9dbfe13fccbccb3593fed5aaf46e09e9490d727c4824a7b4e428dd187fda49b741c3bc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
